/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as P4PreviewRouteImport } from './routes/p4-preview'
import { Route as P4PipelineRouteImport } from './routes/p4-pipeline'
import { Route as P4DashboardRouteImport } from './routes/p4-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as ApplyCollectorRouteImport } from './routes/apply-collector'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectorIndexRouteImport } from './routes/collector.index'
import { Route as PickupOffersRouteImport } from './routes/pickup.offers'
import { Route as PickupNewRouteImport } from './routes/pickup.new'
import { Route as CollectorPointsRouteImport } from './routes/collector.points'
import { Route as CollectorPickupsRouteImport } from './routes/collector.pickups'
import { Route as CollectorOffersRouteImport } from './routes/collector.offers'
import { Route as CollectorDashboardRouteImport } from './routes/collector.dashboard'
import { Route as CollectorCompanyRouteImport } from './routes/collector.company'
import { Route as CollectorCampaignsRouteImport } from './routes/collector.campaigns'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const P4PreviewRoute = P4PreviewRouteImport.update({
  id: '/p4-preview',
  path: '/p4-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const P4PipelineRoute = P4PipelineRouteImport.update({
  id: '/p4-pipeline',
  path: '/p4-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const P4DashboardRoute = P4DashboardRouteImport.update({
  id: '/p4-dashboard',
  path: '/p4-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyCollectorRoute = ApplyCollectorRouteImport.update({
  id: '/apply-collector',
  path: '/apply-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIndexRoute = CollectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectorRoute,
} as any)
const PickupOffersRoute = PickupOffersRouteImport.update({
  id: '/pickup/offers',
  path: '/pickup/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupNewRoute = PickupNewRouteImport.update({
  id: '/pickup/new',
  path: '/pickup/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorPointsRoute = CollectorPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorPickupsRoute = CollectorPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorOffersRoute = CollectorOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorDashboardRoute = CollectorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorCompanyRoute = CollectorCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorCampaignsRoute = CollectorCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => CollectorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apply-collector': typeof ApplyCollectorRoute
  '/collector': typeof CollectorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/p4-dashboard': typeof P4DashboardRoute
  '/p4-pipeline': typeof P4PipelineRoute
  '/p4-preview': typeof P4PreviewRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/setup-password': typeof SetupPasswordRoute
  '/vouchers': typeof VouchersRoute
  '/collector/campaigns': typeof CollectorCampaignsRoute
  '/collector/company': typeof CollectorCompanyRoute
  '/collector/dashboard': typeof CollectorDashboardRoute
  '/collector/offers': typeof CollectorOffersRoute
  '/collector/pickups': typeof CollectorPickupsRoute
  '/collector/points': typeof CollectorPointsRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
  '/collector/': typeof CollectorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apply-collector': typeof ApplyCollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/p4-dashboard': typeof P4DashboardRoute
  '/p4-pipeline': typeof P4PipelineRoute
  '/p4-preview': typeof P4PreviewRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/setup-password': typeof SetupPasswordRoute
  '/vouchers': typeof VouchersRoute
  '/collector/campaigns': typeof CollectorCampaignsRoute
  '/collector/company': typeof CollectorCompanyRoute
  '/collector/dashboard': typeof CollectorDashboardRoute
  '/collector/offers': typeof CollectorOffersRoute
  '/collector/pickups': typeof CollectorPickupsRoute
  '/collector/points': typeof CollectorPointsRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
  '/collector': typeof CollectorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apply-collector': typeof ApplyCollectorRoute
  '/collector': typeof CollectorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/p4-dashboard': typeof P4DashboardRoute
  '/p4-pipeline': typeof P4PipelineRoute
  '/p4-preview': typeof P4PreviewRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/setup-password': typeof SetupPasswordRoute
  '/vouchers': typeof VouchersRoute
  '/collector/campaigns': typeof CollectorCampaignsRoute
  '/collector/company': typeof CollectorCompanyRoute
  '/collector/dashboard': typeof CollectorDashboardRoute
  '/collector/offers': typeof CollectorOffersRoute
  '/collector/pickups': typeof CollectorPickupsRoute
  '/collector/points': typeof CollectorPointsRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
  '/collector/': typeof CollectorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/apply-collector'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/p4-dashboard'
    | '/p4-pipeline'
    | '/p4-preview'
    | '/register'
    | '/settings'
    | '/setup-password'
    | '/vouchers'
    | '/collector/campaigns'
    | '/collector/company'
    | '/collector/dashboard'
    | '/collector/offers'
    | '/collector/pickups'
    | '/collector/points'
    | '/pickup/new'
    | '/pickup/offers'
    | '/collector/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/apply-collector'
    | '/dashboard'
    | '/login'
    | '/p4-dashboard'
    | '/p4-pipeline'
    | '/p4-preview'
    | '/register'
    | '/settings'
    | '/setup-password'
    | '/vouchers'
    | '/collector/campaigns'
    | '/collector/company'
    | '/collector/dashboard'
    | '/collector/offers'
    | '/collector/pickups'
    | '/collector/points'
    | '/pickup/new'
    | '/pickup/offers'
    | '/collector'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/apply-collector'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/p4-dashboard'
    | '/p4-pipeline'
    | '/p4-preview'
    | '/register'
    | '/settings'
    | '/setup-password'
    | '/vouchers'
    | '/collector/campaigns'
    | '/collector/company'
    | '/collector/dashboard'
    | '/collector/offers'
    | '/collector/pickups'
    | '/collector/points'
    | '/pickup/new'
    | '/pickup/offers'
    | '/collector/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ApplyCollectorRoute: typeof ApplyCollectorRoute
  CollectorRoute: typeof CollectorRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  P4DashboardRoute: typeof P4DashboardRoute
  P4PipelineRoute: typeof P4PipelineRoute
  P4PreviewRoute: typeof P4PreviewRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
  VouchersRoute: typeof VouchersRoute
  PickupNewRoute: typeof PickupNewRoute
  PickupOffersRoute: typeof PickupOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p4-preview': {
      id: '/p4-preview'
      path: '/p4-preview'
      fullPath: '/p4-preview'
      preLoaderRoute: typeof P4PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p4-pipeline': {
      id: '/p4-pipeline'
      path: '/p4-pipeline'
      fullPath: '/p4-pipeline'
      preLoaderRoute: typeof P4PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p4-dashboard': {
      id: '/p4-dashboard'
      path: '/p4-dashboard'
      fullPath: '/p4-dashboard'
      preLoaderRoute: typeof P4DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-collector': {
      id: '/apply-collector'
      path: '/apply-collector'
      fullPath: '/apply-collector'
      preLoaderRoute: typeof ApplyCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/': {
      id: '/collector/'
      path: '/'
      fullPath: '/collector/'
      preLoaderRoute: typeof CollectorIndexRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/pickup/offers': {
      id: '/pickup/offers'
      path: '/pickup/offers'
      fullPath: '/pickup/offers'
      preLoaderRoute: typeof PickupOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/new': {
      id: '/pickup/new'
      path: '/pickup/new'
      fullPath: '/pickup/new'
      preLoaderRoute: typeof PickupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/points': {
      id: '/collector/points'
      path: '/points'
      fullPath: '/collector/points'
      preLoaderRoute: typeof CollectorPointsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/pickups': {
      id: '/collector/pickups'
      path: '/pickups'
      fullPath: '/collector/pickups'
      preLoaderRoute: typeof CollectorPickupsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/offers': {
      id: '/collector/offers'
      path: '/offers'
      fullPath: '/collector/offers'
      preLoaderRoute: typeof CollectorOffersRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/dashboard': {
      id: '/collector/dashboard'
      path: '/dashboard'
      fullPath: '/collector/dashboard'
      preLoaderRoute: typeof CollectorDashboardRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/company': {
      id: '/collector/company'
      path: '/company'
      fullPath: '/collector/company'
      preLoaderRoute: typeof CollectorCompanyRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/campaigns': {
      id: '/collector/campaigns'
      path: '/campaigns'
      fullPath: '/collector/campaigns'
      preLoaderRoute: typeof CollectorCampaignsRouteImport
      parentRoute: typeof CollectorRoute
    }
  }
}

interface CollectorRouteChildren {
  CollectorCampaignsRoute: typeof CollectorCampaignsRoute
  CollectorCompanyRoute: typeof CollectorCompanyRoute
  CollectorDashboardRoute: typeof CollectorDashboardRoute
  CollectorOffersRoute: typeof CollectorOffersRoute
  CollectorPickupsRoute: typeof CollectorPickupsRoute
  CollectorPointsRoute: typeof CollectorPointsRoute
  CollectorIndexRoute: typeof CollectorIndexRoute
}

const CollectorRouteChildren: CollectorRouteChildren = {
  CollectorCampaignsRoute: CollectorCampaignsRoute,
  CollectorCompanyRoute: CollectorCompanyRoute,
  CollectorDashboardRoute: CollectorDashboardRoute,
  CollectorOffersRoute: CollectorOffersRoute,
  CollectorPickupsRoute: CollectorPickupsRoute,
  CollectorPointsRoute: CollectorPointsRoute,
  CollectorIndexRoute: CollectorIndexRoute,
}

const CollectorRouteWithChildren = CollectorRoute._addFileChildren(
  CollectorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ApplyCollectorRoute: ApplyCollectorRoute,
  CollectorRoute: CollectorRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  P4DashboardRoute: P4DashboardRoute,
  P4PipelineRoute: P4PipelineRoute,
  P4PreviewRoute: P4PreviewRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SetupPasswordRoute: SetupPasswordRoute,
  VouchersRoute: VouchersRoute,
  PickupNewRoute: PickupNewRoute,
  PickupOffersRoute: PickupOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
