/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickupOffersRouteImport } from './routes/pickup.offers'
import { Route as PickupNewRouteImport } from './routes/pickup.new'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupOffersRoute = PickupOffersRouteImport.update({
  id: '/pickup/offers',
  path: '/pickup/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupNewRoute = PickupNewRouteImport.update({
  id: '/pickup/new',
  path: '/pickup/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vouchers': typeof VouchersRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vouchers': typeof VouchersRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/vouchers': typeof VouchersRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/vouchers'
    | '/pickup/new'
    | '/pickup/offers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/vouchers'
    | '/pickup/new'
    | '/pickup/offers'
  id:
    | '__root__'
    | '/'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/vouchers'
    | '/pickup/new'
    | '/pickup/offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectorRoute: typeof CollectorRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VouchersRoute: typeof VouchersRoute
  PickupNewRoute: typeof PickupNewRoute
  PickupOffersRoute: typeof PickupOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/offers': {
      id: '/pickup/offers'
      path: '/pickup/offers'
      fullPath: '/pickup/offers'
      preLoaderRoute: typeof PickupOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/new': {
      id: '/pickup/new'
      path: '/pickup/new'
      fullPath: '/pickup/new'
      preLoaderRoute: typeof PickupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectorRoute: CollectorRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VouchersRoute: VouchersRoute,
  PickupNewRoute: PickupNewRoute,
  PickupOffersRoute: PickupOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
