/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as P4PreviewRouteImport } from './routes/p4-preview'
import { Route as P4PipelineRouteImport } from './routes/p4-pipeline'
import { Route as P4DashboardRouteImport } from './routes/p4-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickupOffersRouteImport } from './routes/pickup.offers'
import { Route as PickupNewRouteImport } from './routes/pickup.new'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const P4PreviewRoute = P4PreviewRouteImport.update({
  id: '/p4-preview',
  path: '/p4-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const P4PipelineRoute = P4PipelineRouteImport.update({
  id: '/p4-pipeline',
  path: '/p4-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const P4DashboardRoute = P4DashboardRouteImport.update({
  id: '/p4-dashboard',
  path: '/p4-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupOffersRoute = PickupOffersRouteImport.update({
  id: '/pickup/offers',
  path: '/pickup/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupNewRoute = PickupNewRouteImport.update({
  id: '/pickup/new',
  path: '/pickup/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/p4-dashboard': typeof P4DashboardRoute
  '/p4-pipeline': typeof P4PipelineRoute
  '/p4-preview': typeof P4PreviewRoute
  '/register': typeof RegisterRoute
  '/vouchers': typeof VouchersRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/p4-dashboard': typeof P4DashboardRoute
  '/p4-pipeline': typeof P4PipelineRoute
  '/p4-preview': typeof P4PreviewRoute
  '/register': typeof RegisterRoute
  '/vouchers': typeof VouchersRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/p4-dashboard': typeof P4DashboardRoute
  '/p4-pipeline': typeof P4PipelineRoute
  '/p4-preview': typeof P4PreviewRoute
  '/register': typeof RegisterRoute
  '/vouchers': typeof VouchersRoute
  '/pickup/new': typeof PickupNewRoute
  '/pickup/offers': typeof PickupOffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/p4-dashboard'
    | '/p4-pipeline'
    | '/p4-preview'
    | '/register'
    | '/vouchers'
    | '/pickup/new'
    | '/pickup/offers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/p4-dashboard'
    | '/p4-pipeline'
    | '/p4-preview'
    | '/register'
    | '/vouchers'
    | '/pickup/new'
    | '/pickup/offers'
  id:
    | '__root__'
    | '/'
    | '/collector'
    | '/dashboard'
    | '/login'
    | '/p4-dashboard'
    | '/p4-pipeline'
    | '/p4-preview'
    | '/register'
    | '/vouchers'
    | '/pickup/new'
    | '/pickup/offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectorRoute: typeof CollectorRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  P4DashboardRoute: typeof P4DashboardRoute
  P4PipelineRoute: typeof P4PipelineRoute
  P4PreviewRoute: typeof P4PreviewRoute
  RegisterRoute: typeof RegisterRoute
  VouchersRoute: typeof VouchersRoute
  PickupNewRoute: typeof PickupNewRoute
  PickupOffersRoute: typeof PickupOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p4-preview': {
      id: '/p4-preview'
      path: '/p4-preview'
      fullPath: '/p4-preview'
      preLoaderRoute: typeof P4PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p4-pipeline': {
      id: '/p4-pipeline'
      path: '/p4-pipeline'
      fullPath: '/p4-pipeline'
      preLoaderRoute: typeof P4PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p4-dashboard': {
      id: '/p4-dashboard'
      path: '/p4-dashboard'
      fullPath: '/p4-dashboard'
      preLoaderRoute: typeof P4DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/offers': {
      id: '/pickup/offers'
      path: '/pickup/offers'
      fullPath: '/pickup/offers'
      preLoaderRoute: typeof PickupOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/new': {
      id: '/pickup/new'
      path: '/pickup/new'
      fullPath: '/pickup/new'
      preLoaderRoute: typeof PickupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectorRoute: CollectorRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  P4DashboardRoute: P4DashboardRoute,
  P4PipelineRoute: P4PipelineRoute,
  P4PreviewRoute: P4PreviewRoute,
  RegisterRoute: RegisterRoute,
  VouchersRoute: VouchersRoute,
  PickupNewRoute: PickupNewRoute,
  PickupOffersRoute: PickupOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
